### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by gau-nernst** [gau-nernst/vision-toolbox#1]
## TODO

Backbones

- [ ] HRNet [[Paper v1]](https://arxiv.org/abs/1902.09212) [[Paper v2]](https://arxiv.org/abs/1908.07919) [[code]](https://github.com/HRNet) [[mmdet]](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/hrnet.py)
- [ ] VOLO? [[paper]](https://arxiv.org/abs/2106.13112)
- [x] PatchConvNet (training results are not good. port weights over to check correctness?)
- [x] VoVNetV1, since ESE is not supported on many edge platforms
- [x] torchvision's RegNet [[paper]](https://arxiv.org/abs/2003.13678) [[code]](https://github.com/pytorch/vision/blob/main/torchvision/models/regnet.py)
- [x] Darknet-YOLOv5 [[code]](https://github.com/ultralytics/yolov5/tree/master/models)

Training

- [ ] (Low priority) JPEG GPU decoding to alleviate CPU bottleneck in data loading for small models [link](http://pytorch.org/vision/stable/io.html#torchvision.io.decode_jpeg)
  - May break torchvision.transforms and Lightning
- [ ] (Low priority) Model EMA
  - PyTorchLightning/pytorch-lightning/issues/10914 -> not a clean solution
  - [torchvision](https://github.com/pytorch/vision/blob/main/references/classification/utils.py)
- [x] Use DataModule to separate data from LightningModule for better readability
- [x] Channels-last memory layout [link](https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html)
  - Good performance gain (RTX3090, with fp16 training). For Darknet-53, 1.4 it/s (w/ JIT) -> 2 it/s (w/o JIT, channels-last)
  - JIT + channels-last is not good: 1.3it/s
- [x] WebDataset
- [ ] (Currently not possible) DALI pipeline
  - NVIDIA/DALI/issues/2978
  - DALI does not support conditional operations. Implementing Trivial Augment will be challenging
